import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useGetItemsQuery } from "../lib/graphql";

const Home: NextPage = () => {
  const [{ data, fetching, error, operation }, executeQuery] =
    useGetItemsQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data?.item.map(({ id }, index) => {
          return <p key={index}>{id}</p>;
        })}
      </main>
    </div>
  );
};

export default Home;
